# Generated by Django 4.2.4 on 2023-12-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_rename_full_name_profile_first_name_profile_active_and_more'),
        ('core', '0014_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.profile'),
        ),
    ]
