# Generated by Django 4.2.4 on 2023-12-08 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_rename_full_name_profile_first_name_profile_active_and_more'),
        ('core', '0018_remove_wishlist_model_user_wishlist_model_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='user',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.profile'),
        ),
    ]
