# Generated by Django 4.2.4 on 2024-01-12 23:34

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cartorder_user_cartorder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ImageField(default='color.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ImageField(default='color1.jpg', upload_to='product-colors')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_colors', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
    ]
