# Generated by Django 4.2.4 on 2024-01-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartorderitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
