# Generated by Django 4.2.4 on 2024-01-16 12:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cartorderitems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
