# Generated by Django 4.2.4 on 2024-01-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartorder_receipt_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
