# Generated by Django 4.2.4 on 2024-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cartorder_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='receipt_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
