# Generated by Django 4.2.4 on 2024-01-20 05:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cartorder_receipt_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='cartorder_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=5, max_length=10, prefix='cart_order_', unique=True),
        ),
    ]
