# Generated by Django 4.2.4 on 2024-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_cartorder_cartorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
