# Generated by Django 4.2.4 on 2024-01-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_cartorderitems_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month_eta',
            field=models.IntegerField(default=30),
        ),
    ]
