# Generated by Django 4.2.4 on 2023-12-13 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_remove_cartorder_user_cartorder_profile'),
        ('userauths', '0007_rename_full_name_profile_first_name_profile_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('estimated_delivery_days', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_type_images/')),
                ('base_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Swatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('base_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='swatch_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SwatchColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('swatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.swatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customized_image', models.ImageField(blank=True, null=True, upload_to='customized_product_images/')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.producttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.profile')),
                ('swatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatch')),
                ('swatch_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatchcolor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customprd_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuv123456789', length=22, max_length=45, prefix='customed_', unique=True)),
                ('service_type', models.CharField(choices=[('make', 'Make'), ('repair', 'Repair')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('percentage_progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], max_length=12)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customproducts_prototype2', to='userauths.profile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customproducts_prototype2', to='core.category')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_customproducts_prototype2', to='userauths.profile')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.producttype')),
                ('swatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatch')),
                ('swatch_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatchcolor')),
            ],
        ),
    ]
