# Generated by Django 4.2.4 on 2023-12-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0002_producttype_applicable_swatches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='swatch',
            field=models.ForeignKey(limit_choices_to={'product_type__id': models.F('product_type__id')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatch'),
        ),
    ]
