# Generated by Django 4.2.4 on 2023-12-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0004_alter_customproduct_swatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='swatch',
            field=models.ForeignKey(limit_choices_to={'id': models.F('product_type__id')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder_prototype2.swatch'),
        ),
    ]
