# Generated by Django 4.2.4 on 2023-12-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0005_alter_customproduct_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productconfiguration',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='productconfiguration',
            name='swatch',
        ),
        migrations.RemoveField(
            model_name='productconfiguration',
            name='swatch_color',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='applicable_swatches',
        ),
        migrations.RemoveField(
            model_name='swatchcolor',
            name='swatch',
        ),
        migrations.DeleteModel(
            name='CustomProduct',
        ),
        migrations.DeleteModel(
            name='ProductConfiguration',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Swatch',
        ),
        migrations.DeleteModel(
            name='SwatchColor',
        ),
    ]
