# Generated by Django 4.2.4 on 2023-12-16 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customorder_prototype2', '0006_remove_productconfiguration_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colors', models.ManyToManyField(to='customorder_prototype2.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('sale_date', models.DateField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.color')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.materialtype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='materialtype',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype'),
        ),
    ]
