# Generated by Django 4.2.4 on 2023-12-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_rename_full_name_profile_first_name_profile_active_and_more'),
        ('customorder_prototype2', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.color')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.materialtype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.profile')),
            ],
        ),
    ]
