# Generated by Django 4.2.4 on 2024-01-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='materialtype',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
