# Generated by Django 4.2.4 on 2024-01-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '0007_rename_full_name_profile_first_name_profile_active_and_more'),
        ('customorder_prototype2', '0009_remove_materialtype_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.profile')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.material')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.material'),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.material')),
            ],
        ),
    ]
