# Generated by Django 4.2.4 on 2024-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0011_producttype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_type/'),
        ),
    ]
