# Generated by Django 4.2.4 on 2024-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0012_alter_producttype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_type/material'),
        ),
    ]
