# Generated by Django 4.2.4 on 2024-01-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0013_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_type/colors'),
        ),
    ]
