# Generated by Django 4.2.4 on 2024-01-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0015_material_fabric_peryard_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='foam_percubicft_price',
        ),
    ]
