# Generated by Django 4.2.4 on 2024-01-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0017_material_foam_percubicft_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foam_percubicft_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foam_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='foam_percubicft_price',
        ),
        migrations.AddField(
            model_name='analytics',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='AdminProfile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='customer_notes',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analytics',
            name='foam_type',
            field=models.ForeignKey(default=650, on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.foamtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='foam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.foamtype'),
            preserve_default=False,
        ),
    ]
