# Generated by Django 4.2.4 on 2024-01-08 16:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0019_alter_customizationorder_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='admin_notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customizationorder',
            name='customer_notes',
            field=models.TextField(),
        ),
    ]
