# Generated by Django 4.2.4 on 2024-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0020_customizationorder_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationorder',
            name='customer_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
