# Generated by Django 4.2.4 on 2024-01-09 05:57

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0021_alter_customizationorder_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='co_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=25, prefix='CO', unique=True),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
