# Generated by Django 4.2.4 on 2024-01-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0023_customizationorder_make_or_repair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to='receipt/'),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='with_downpayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='month_eta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
