# Generated by Django 4.2.4 on 2024-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0025_customizationorder_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='foamtype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
