# Generated by Django 4.2.4 on 2024-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0026_foamtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
