# Generated by Django 4.2.4 on 2024-01-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0027_customizationorder_date_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizationorder',
            old_name='Profile',
            new_name='profile',
        ),
    ]
