# Generated by Django 4.2.4 on 2024-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0028_rename_profile_customizationorder_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='selection_count',
            new_name='make_orders',
        ),
        migrations.AddField(
            model_name='analytics',
            name='repair_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('product_type', 'material', 'color', 'foam_type')},
        ),
    ]
