# Generated by Django 4.2.4 on 2024-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0029_rename_selection_count_analytics_make_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='total_orders',
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_orders_per_month',
            field=models.JSONField(default=dict),
        ),
    ]
