# Generated by Django 4.2.4 on 2024-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0030_remove_analytics_total_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='receipt_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customizationorder',
            name='AdminProfile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
