# Generated by Django 4.2.4 on 2024-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0032_alter_customizationorder_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
