# Generated by Django 4.2.4 on 2024-01-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0033_alter_customizationorder_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationorder',
            name='customization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='estimated_date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='estimated_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999, null=True),
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='purpose',
            field=models.CharField(choices=[('private', 'Private'), ('business', 'Business'), ('government', 'Government')], default='Private', max_length=30),
        ),
        migrations.AlterField(
            model_name='customizationorder',
            name='AdminProfile',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customizationorder',
            name='make_or_repair',
            field=models.CharField(choices=[('make', 'Make'), ('repair', 'Repair')], default='MAKE', max_length=20),
        ),
    ]
