# Generated by Django 4.2.4 on 2024-01-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0034_customizationorder_customization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationorder',
            name='customization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('production starts', 'Production Starts'), ('drafting', 'Drafting'), ('cutting phase', 'Cutting'), ('assembly', 'Assembly'), ('seaming', 'Seaming'), ('padding', 'Padding'), ('detailing', 'Detailing'), ('quality control', 'Quality Control'), ('to be picked up', 'To Be Picked Up'), ('done', 'Done')], default='pending', max_length=30),
        ),
    ]
