# Generated by Django 4.2.4 on 2024-02-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customorder_prototype2', '0035_alter_customizationorder_customization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(max_length=100)),
                ('size_spec', models.CharField(max_length=500)),
                ('size_desc', models.CharField(max_length=500)),
                ('fabric_yard_v2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foam_amount_v2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_eta_v2', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_size')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='customizationorder',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customorder_prototype2.producttypesizes'),
        ),
    ]
