# Generated by Django 4.2.4 on 2023-10-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('estimated_delivery_days', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_type_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Swatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SwatchColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('swatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customorder.swatch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_delivery_days', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder.producttype')),
                ('swatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder.swatch')),
                ('swatch_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customorder.swatchcolor')),
            ],
        ),
    ]
