# Generated by Django 4.2.4 on 2023-10-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder', '0002_producttype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='swatch',
            name='base_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='swatch_images/'),
        ),
    ]
