# Generated by Django 4.2.4 on 2023-10-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder', '0003_swatch_base_price_swatch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='estimated_delivery_days',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='progress',
            field=models.CharField(default='In Progress', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customproduct',
            name='service_type',
            field=models.CharField(default='Make', max_length=100),
            preserve_default=False,
        ),
    ]
