# Generated by Django 4.2.4 on 2023-10-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customorder', '0004_remove_customproduct_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='progress',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='service_type',
            field=models.CharField(choices=[('make', 'Make'), ('repair', 'Repair')], max_length=10),
        ),
    ]
