# Generated by Django 4.2.4 on 2023-10-25 03:19

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customorder', '0005_alter_customproduct_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='customprd_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuv123456789', length=22, max_length=25, prefix='customed_', unique=True),
        ),
    ]
