# Generated by Django 4.2.4 on 2023-10-25 03:20

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customorder', '0006_customproduct_customprd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='customprd_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuv123456789', length=22, max_length=45, prefix='customed_', unique=True),
        ),
    ]
